server:
  port: 8084
#  应用名称 nacos中的服务名称
spring:
  application:
    name: product-service
  cloud:
    #    nacos 相关信息
    nacos:
      server-addr: 43.143.19.102:8849
      discovery:
        username: nacos
        password: nacos
        namespace: public