server:
  port: 8082
#  应用名称 nacos中的服务名称
spring:
  application:
    name: store-service
  cloud:
    #    nacos 相关信息
    nacos:
      server-addr: 43.143.19.102:8849
      discovery:
        username: nacos
        password: nacos
        namespace: public
    alibaba:
      seata:
        tx-service-group: default_tx_group
  # 数据源
  datasource:
    username: root
    password: 1476154535@qwer
    url: jdbc:mysql://sh-cynosdbmysql-grp-dqktvhju.sql.tencentcdb.com:26578/seata_stock?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    #初始化时运行sql脚本
    schema: classpath:sql/schema.sql
    initialization-mode: never
#设置mybatis
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  #config-location: classpath:mybatis-config.xml
  typeAliasesPackage: com.trojan.store.store
  configuration:
    mapUnderscoreToCamelCase: on


seata:
  registry:
    # 配置seata的注册中心， 告诉seata client 怎么去访问seata server(TC)
    type: nacos
    nacos:
      server-addr: 43.143.19.102:8849  # seata server 所在的nacos服务地址
      application: seata-server    # seata server 的服务名seata-server ，如果没有修改可以不配
      username: nacos
      password: nacos
      group: SEATA_GROUP          # seata server 所在的组，默认就是SEATA_GROUP，没有改也可以不配
  config:
    type: nacos
    nacos:
      server-addr: 43.143.19.102:8849
      username: nacos
      password: nacos
      group: SEATA_GROUP