server:
  port: 8081
#  应用名称 nacos中的服务名称
spring:
  application:
    name: order.service
  cloud:
    sentinel:
      transport:
#        使用sentinel控制面板  sentinel的地址及端口
        dashboard: localhost:8050

    #    nacos 相关信息
#    nacos:
#      server-addr: 43.143.19.102:8849
#      discovery:
#        username: nacos
#        password: nacos
#        namespace: dev

  #    loadbalancer:
#      ribbon:
#        enabled: false

#
  #    com.trojan.order.controller: debug
#定义ribbon负载均衡规则
store-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.trojan.ribbon.rule.CustomizeRule

#    全局日志定义
logging:
  level:
    com.trojan.order.feign: info
feign:
  client:
    config:
      product-service:
#        定义feign的日志输出模式
        loggerLevel: BASIC
        connecTimeout: 5000 #请求服务的时间
        readTimeout: 3000 #服务端业务处理返回的时间
  sentinel:
#    默认值为false
    enabled: true
